### ISSUE TITLE
It took 300ms-400ms to sign 100 times

### ISSUE THREAD

**Issue by vae520283995** [starkbank/ecdsa-java#13]
@Test
    public void testSign() {
        PrivateKey privateKey = new PrivateKey();
        String message = "This is a text message";
        long a = System.nanoTime();
        for (int i = 0; i < 100; i++) {
            Ecdsa.sign(message, privateKey);
        }
        long b = System.nanoTime();
        System.out.println((b - a) / 1000000);
    }

**Comment by cdottori-stark** [comment]
The signing and verification time oscillates with processor speed etc., so the numbers we displayed at our README are only used as a comparison with other ECDSA libraries/systems. Still, glad to hear its running faster on your hardware!
