### ISSUE TITLE
Add LICENSE for Java, PHP, Ruby, and Node

### ISSUE THREAD

**Issue by childish-sambino** [starkbank/ecdsa-java#5]
Considering using these libraries but I don't see a LICNESE file in each repo. Could you add a LICENSE for the Java, PHP, Ruby, and Node libs and include in a new release?

**Comment by cdottori-stark** [comment]
All LICENSE files added, thanks for the input!

**Comment by childish-sambino** [comment]
Awesome. Thanks!
